### Generator configuration settings:

## where to generate the project:
project_path=${home}/IdeaProjects/GeneratedSpringBootProject
## target SB version:
springboot_version=4.0.3

## number of bean modules:
modules_amount=3
## number of modules with xml configs:
xml_modules_amount=3
## number of JPA modules:
jpa_modules_amount=3

## number of @Component beans in each bean module:
components_amount=3
## number of @Bean beans in each bean module:
beans_amount=3

## number of beans in each xml bean module:
xml_classes_amount=3

## number of entities in each JPA module:
entities_amount=3
## number of entity columns:
columns_amount=3



