package com.mytest.springBootProjectGenerator;


import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.mytest.springBootProjectGenerator.Utils.*;

public class GenerateJPAModule {
    private final int moduleNumber;
    private final int entitiesAmount;
    private final int columnsAmount;
    private final String packageName;
    private final String moduleName;
    private final String path;

    public GenerateJPAModule(int moduleNumber, int entitiesAmount, int columnsAmount, String packageName, String moduleName, String path) {
        this.moduleNumber = moduleNumber;
        this.entitiesAmount = entitiesAmount;
        this.columnsAmount = columnsAmount;
        this.packageName = packageName;
        this.moduleName = moduleName;
        this.path = path;
    }

    public List<BeanProperties> generateAll() throws IOException {
        List<BeanProperties> repositories = generateModule();
        File jpaModuleConfigClassFile = new File(path + "/" + moduleName + "/src/main/java/com/mytests/spring/" + "jpa/"+packageName + "/JpaModule" + moduleNumber + "Configuration.java");
        File sourceFile = new File("./src/main/resources/templates/jpaModuleConfigClass.txt");
        copyTemplateFile(sourceFile, jpaModuleConfigClassFile);
        modifyFile(jpaModuleConfigClassFile, "X", String.valueOf(moduleNumber));
        return repositories;
    }

    private List<BeanProperties> generateModule() throws IOException {
        String sourcePom = "./src/main/resources/templates/jpa_module_pom.txt";
        String moduleDir = createModule(path, moduleName, sourcePom);
        List<BeanProperties> repoList = new ArrayList<>();
        List<String> entityNames = new ArrayList<>();
        for (int i = 0; i < entitiesAmount; i++) {
            String entity = generateEntity(i, columnsAmount);
            entityNames.add(entity);
            String repo = generateRepository(entity,columnsAmount);
            repoList.add(new BeanProperties("com.mytests.spring.jpa." + packageName, repo, repo.substring(0, 1).toLowerCase()+repo.substring(1), entity));
        }
        generateSchemaAndData(moduleDir, entityNames);
        return repoList;
    }
    private String generateEntity(int entityNumber, int fieldsAmount){

        String beanClassName = "Entity"+ moduleNumber + "_" + entityNumber;
        PrintWriter writer = createFile(path + "/" + moduleName + "/src/main/java/com/mytests/spring/", "jpa/"+packageName, beanClassName, ".java");
        if (writer != null) {
            writer.println("package com.mytests.spring.jpa." + packageName + ";\n\n");
            writer.println("""
                    import jakarta.persistence.Entity;
                    import jakarta.persistence.GeneratedValue;
                    import jakarta.persistence.Id;
                    
                    @Entity
                    """);
            writer.println("public class " + beanClassName + "  {\n");
            writer.println("""
                    
                        @Id @GeneratedValue
                        private Long id;
                    
                        public void setId(Long id) {
                            this.id = id;
                        }
                    
                        public Long getId() {
                            return id;
                        }
                    """);
            for (int i = 0; i < fieldsAmount; i++) {
                writer.println("   private String column" + i + ";\n");
            }

            for (int i = 0; i < fieldsAmount; i++) {
                writer.println("   public String getColumn" + i + "() {");
                writer.println("     return this.column" + i + "; \n    }\n");
            }
            for (int i = 0; i < fieldsAmount; i++) {
                writer.println("   public void setColumn" + i + "( String c) {");
                writer.println("     this.column" + i + " = c; \n    }\n");
            }
            writer.println("   public " + beanClassName + "() { } \n");
            writer.println(" }");
            writer.close();
        }
       return beanClassName;
    }

    private void generateSchemaAndData(String moduleDir, List<String> entityNames) throws IOException {
        PrintWriter schemaWriter = new PrintWriter(moduleDir + "/src/main/resources/schema.sql", "UTF-8");
        PrintWriter dataWriter = new PrintWriter(moduleDir + "/src/main/resources/data.sql", "UTF-8");

        for (String entityName : entityNames) {
            String tableName = entityName.toLowerCase();

            schemaWriter.println("CREATE TABLE " + tableName + " (");
            schemaWriter.println("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,");
            for (int i = 0; i < columnsAmount - 1; i++) {
                schemaWriter.println("    column" + i + " VARCHAR(30),");
            }
            schemaWriter.println("    column" + (columnsAmount - 1) + " VARCHAR(30)");
            schemaWriter.println(");\n");

            StringBuilder cols = new StringBuilder("(");
            for (int i = 0; i < columnsAmount; i++) {
                cols.append("column").append(i);
                if (i < columnsAmount - 1) cols.append(", ");
            }
            cols.append(")");

            for (int row = 0; row < 3; row++) {
                StringBuilder vals = new StringBuilder("(");
                for (int col = 0; col < columnsAmount; col++) {
                    vals.append("'").append(tableName).append("_r").append(row).append("_c").append(col).append("'");
                    if (col < columnsAmount - 1) vals.append(", ");
                }
                vals.append(")");
                dataWriter.println("INSERT INTO " + tableName + " " + cols + " VALUES " + vals + ";");
            }
            dataWriter.println();
        }

        schemaWriter.close();
        dataWriter.close();
    }

    private String generateRepository(String entityName, int fieldsAmount) throws IOException {

        String beanClassName = entityName+"Repository";
        PrintWriter writer = createFile(path + "/" + moduleName + "/src/main/java/com/mytests/spring/", "jpa/"+packageName, beanClassName, ".java");
        if (writer != null) {

            writer.println("package com.mytests.spring.jpa." + packageName + ";\n\n");
            writer.println("""
                    import org.springframework.data.jpa.repository.Query;
                    import org.springframework.data.repository.CrudRepository;
                    import org.springframework.data.repository.query.Param;
                    import java.util.List;
                    
                    """);
            writer.println("public interface " + beanClassName + " extends CrudRepository<" + entityName + ", Integer> {\n");
            writer.println("   List<" + entityName + "> findAll();\n");
            for (int i = 0; i < fieldsAmount; i++) {
                writer.println("   @Query(\"select e from " + entityName + " e where e.column" + i + " = :arg\")");
                writer.println("   List<" + entityName + "> customQuery" + i + "(@Param(\"arg\") String arg) ;\n");
            }
            writer.println(" }");
            writer.close();
        }
        return beanClassName;
    }
}
